apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-ds
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: PostgreSQL
    type: postgres
    uid: postgres-ds
    access: proxy
    url: $PG_DS_HOST:$PG_DS_PORT
    database: $PG_DS_DATABASE
    user: $PG_DS_USER
    secureJsonData:
      password: $PG_DS_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1800
    editable: false